worker_types:

  - worker_type: appservices-3-beetmover
    provisioner: scriptworker-k8s
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-applicationservices-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-beetmover
    provisioner: scriptworker-k8s
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 40
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1


  - worker_type: mobile-3-beetmover
    provisioner: scriptworker-k8s
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-mobile-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-3-beetmover
    provisioner: scriptworker-k8s
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-1-beetmover
    provisioner: scriptworker-k8s
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-balrog
    provisioner: scriptworker-k8s
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-1-balrog
    provisioner: scriptworker-k8s
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-3-balrog
    provisioner: scriptworker-k8s
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-1-balrog
    provisioner: scriptworker-k8s
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-fake-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1
