worker_types:

  - worker_type: appservices-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-applicationservices-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 80
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1


  - worker_type: mobile-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-mobile-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-1-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-balrog
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 45
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-1-balrog
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-3-balrog
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: comm-1-balrog
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-fake-thunderbird-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-addon
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-addon
    deployment_name: addon-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 240
        sla_seconds: 480
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-1-addon
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-addon
    deployment_name: addon-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 240
        sla_seconds: 480
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-t-signing
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-fake-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1

  - worker_type: gecko-3-signing
    provisioner: scriptworker-k8s
    root_url: "https://taskcluster.net"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-firefox-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 100
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 1
