worker_types:

  - worker_type: appservices-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefoxci-applicationservices-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefoxci-gecko-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 80
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 0


  - worker_type: mobile-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefoxci-mobile-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: comm-3-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefoxci-comm-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-1-beetmover
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-beetmover
    deployment_name: beetmover-prod-relengworker-firefoxci-gecko-1-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 120
        sla_seconds: 240
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-3-balrog
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefoxci-gecko-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 25
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-1-balrog
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefoxci-gecko-1-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: comm-3-balrog
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefoxci-comm-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: comm-1-balrog
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-balrog
    deployment_name: balrog-prod-relengworker-firefoxci-comm-1-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-3-addon
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-addon
    deployment_name: addon-prod-relengworker-firefoxci-gecko-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 240
        sla_seconds: 480
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-1-addon
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-addon
    deployment_name: addon-prod-relengworker-firefoxci-gecko-1-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 10
        avg_task_duration: 240
        sla_seconds: 480
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-t-signing
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-firefoxci-gecko-t-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: gecko-3-signing
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-firefoxci-gecko-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 100
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: mobile-3-signing
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-firefoxci-mobile-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0

  - worker_type: comm-3-signing
    provisioner: scriptworker-k8s
    root_url: "https://firefox-ci-tc.services.mozilla.com"
    deployment_namespace: prod-signing
    deployment_name: signing-prod-relengworker-firefoxci-comm-3-1
    autoscale:
      algorithm: sla
      args:
        max_replicas: 20
        avg_task_duration: 60
        sla_seconds: 120
        capacity_ratio: 1.0
        min_replicas: 0
